name: Checking code quality

on:
  push:
    paths:
      - 'renovate.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setting up Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: validating renovate config
        run: npx --package renovate -c 'renovate-config-validator'
