name: Checking code quality

on:
  push:
    paths:
      - 'renovate.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Setting up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: validating renovate config
        run: npx --package renovate -c 'renovate-config-validator'
