name: Checking code quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setting up Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: npm install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: |
          npm run test:ci
          npx codecov@3.0.2

      - name: build
        run: npm run build
